// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW3UN2h7mwC94EhtT_j_wHL-nhknkL9yQ',
    appId: '1:543987647187:web:f4f15ace88e44b99b38a26',
    messagingSenderId: '543987647187',
    projectId: 'pupuseriachilin',
    authDomain: 'pupuseriachilin.firebaseapp.com',
    storageBucket: 'pupuseriachilin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1tCyNfcCWbXNvs5lyhTSc48uVX8XHyB8',
    appId: '1:543987647187:android:096771e09a47c715b38a26',
    messagingSenderId: '543987647187',
    projectId: 'pupuseriachilin',
    storageBucket: 'pupuseriachilin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0mmfdwR75ygFmqbVeqmsFdsgQ4HwR57U',
    appId: '1:543987647187:ios:59985d5e401bc6deb38a26',
    messagingSenderId: '543987647187',
    projectId: 'pupuseriachilin',
    storageBucket: 'pupuseriachilin.appspot.com',
    androidClientId: '543987647187-gm21oq8541om66818eopsm3n9dbl6g3d.apps.googleusercontent.com',
    iosClientId: '543987647187-ee4smmfrlj34mp8huub9dpsg54k0nqr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
